import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/app/Proviers';
import React from 'react';
import MainHeader from '@/app/_components/layouts/MainHeader';
import MainFooter from '@/app/_components/layouts/MainFooter';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col items-center`}>
        <MainHeader />
        <main className="w-full max-w-[75rem] pt-8">
          <Providers>{children}</Providers>
        </main>
        <MainFooter />
      </body>
    </html>
  );
}
