import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/app/Proviers';
import React from 'react';
import MainHeader from '@/app/_components/layouts/MainHeader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center`}>
        <div className="w-[75rem]">
          <MainHeader />
          <main>
            <Providers>{children}</Providers>
          </main>
          <footer>footer</footer>
        </div>
      </body>
    </html>
  );
}
